In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score

In [2]:
df = pd.read_csv("C:/Users/mohad/Downloads/raw_wholesale_customers.csv")

print(df.head())

print()

print(df.info())

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen 

In [3]:
features = [
    "Fresh",
    "Milk",
    "Grocery",
    "Frozen",
    "Detergents_Paper",
    "Delicassen"
]

X = df[features].copy()

print(X.head())

   Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0  12669  9656     7561     214              2674        1338
1   7057  9810     9568    1762              3293        1776
2   6353  8808     7684    2405              3516        7844
3  13265  1196     4221    6404               507        1788
4  22615  5410     7198    3915              1777        5185


In [4]:
for col in features:

    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    X[col] = X[col].clip(lower, upper)

    print(col)
    print("Lower Bound:", lower)
    print("Upper Bound:", upper)
    print()

Fresh
Lower Bound: -17581.25
Upper Bound: 37642.75

Milk
Lower Bound: -6952.875
Upper Bound: 15676.125

Grocery
Lower Bound: -10601.125
Upper Bound: 23409.875

Frozen
Lower Bound: -3475.75
Upper Bound: 7772.25

Detergents_Paper
Lower Bound: -5241.125
Upper Bound: 9419.875

Delicassen
Lower Bound: -1709.75
Upper Bound: 3938.25



In [5]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaled Shape:", X_scaled.shape)

print()

print(X_scaled[:5])

Scaled Shape: (440, 6)

[[ 0.12857261  1.05158597  0.04926747 -0.95324427  0.09579175  0.06589216]
 [-0.42162716  1.08673463  0.35386453 -0.30973493  0.30651872  0.47075856]
 [-0.49064723  0.85804007  0.06793486 -0.04243744  0.38243489  2.46943983]
 [ 0.18700437 -0.87930823 -0.45763545  1.61996169 -0.64192284  0.48185079]
 [ 1.10367719  0.08248706 -0.00582407  0.58527516 -0.20957511  2.46943983]]


In [6]:
sse = []

for k in range(1,11):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init="auto"
    )

    model.fit(X_scaled)

    sse.append(model.inertia_)

print("SSE Values")

for k,value in zip(range(1,11),sse):

    print(f"k = {k}  -->  SSE = {value:.2f}")

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Window

SSE Values
k = 1  -->  SSE = 2640.00
k = 2  -->  SSE = 1728.19
k = 3  -->  SSE = 1363.45
k = 4  -->  SSE = 1202.41
k = 5  -->  SSE = 1070.15
k = 6  -->  SSE = 964.76
k = 7  -->  SSE = 921.14
k = 8  -->  SSE = 776.63
k = 9  -->  SSE = 726.88
k = 10  -->  SSE = 707.41


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Window

In [7]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init="auto"
)

kmeans.fit(X_scaled)

df["Cluster"] = kmeans.labels_

print(df.head())

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  \
0        2       3  12669  9656     7561     214              2674   
1        2       3   7057  9810     9568    1762              3293   
2        2       3   6353  8808     7684    2405              3516   
3        1       3  13265  1196     4221    6404               507   
4        2       3  22615  5410     7198    3915              1777   

   Delicassen  Cluster  
0        1338        0  
1        1776        0  
2        7844        0  
3        1788        3  
4        5185        3  


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(


In [8]:
silhouette = silhouette_score(
    X_scaled,
    kmeans.labels_
)

dbi = davies_bouldin_score(
    X_scaled,
    kmeans.labels_
)

print("Silhouette Score:", silhouette)

print("Davies-Bouldin Index:", dbi)

Silhouette Score: 0.28305439449159625
Davies-Bouldin Index: 1.270058546306858


In [9]:
agg = AgglomerativeClustering(
    n_clusters=5
)

agg_labels = agg.fit_predict(X_scaled)

df["AgglomerativeCluster"] = agg_labels

print(df.head())

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  \
0        2       3  12669  9656     7561     214              2674   
1        2       3   7057  9810     9568    1762              3293   
2        2       3   6353  8808     7684    2405              3516   
3        1       3  13265  1196     4221    6404               507   
4        2       3  22615  5410     7198    3915              1777   

   Delicassen  Cluster  AgglomerativeCluster  
0        1338        0                     4  
1        1776        0                     4  
2        7844        0                     0  
3        1788        3                     3  
4        5185        3                     0  


In [10]:
kmeans_score = silhouette_score(
    X_scaled,
    kmeans.labels_
)

agg_score = silhouette_score(
    X_scaled,
    agg_labels
)

print("K-Means Silhouette Score")

print(kmeans_score)

print()

print("Agglomerative Silhouette Score")

print(agg_score)

K-Means Silhouette Score
0.28305439449159625

Agglomerative Silhouette Score
0.21848258044114816


In [11]:
if kmeans_score > agg_score:

    print("K-Means produced better separated clusters.")

else:

    print("Agglomerative Clustering produced better separated clusters.")

K-Means produced better separated clusters.


In [12]:
sample = df.loc[
    [0,5,10],
    [
        "Fresh",
        "Milk",
        "Grocery",
        "Frozen",
        "Detergents_Paper",
        "Delicassen",
        "Channel",
        "Region",
        "Cluster",
        "AgglomerativeCluster"
    ]
]

print(sample)

    Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen  Channel  \
0   12669  9656     7561     214              2674        1338        2   
5    9413  8259     5126     666              1795        1451        2   
10   3366  5403    12974    4400              5977        1744        2   

    Region  Cluster  AgglomerativeCluster  
0        3        0                     4  
5        3        0                     4  
10       3        0                     4  


In [13]:
df.to_csv(
    "segmented_wholesale_customers.csv",
    index=False
)

print("Dataset Saved Successfully.")

Dataset Saved Successfully.
